export const ErrorCode = {
  // Generic
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  ACCESS_DENIED: "ACCESS_DENIED",

  // Sessions
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_ALREADY_REVOKED: "SESSION_ALREADY_REVOKED",

  // Auth
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  INVALID_TOKEN_TYPE: "INVALID_TOKEN_TYPE",
  REFRESH_TOKEN_REVOKED: "REFRESH_TOKEN_REVOKED",
  SESSION_REVOKED: "SESSION_REVOKED",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  REFRESH_TOKEN_NOT_PASSED: "REFRESH_TOKEN_NOT_PASSED",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_USED: "TOKEN_USED",
  TOKEN_INVALID: "TOKEN_INVALID",
  ACCOUNT_UNAVAILABLE: "ACCOUNT_UNAVAILABLE",
  ACCOUNT_SCHEDULED_FOR_DELETION: "ACCOUNT_SCHEDULED_FOR_DELETION",
  ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  EMAIL_MISMATCH: "EMAIL_MISMATCH",
  ALREADY_SCHEDULED_FOR_DELETION: "ALREADY_SCHEDULED_FOR_DELETION",
  SAME_PASSWORD: "SAME_PASSWORD",
  SAME_EMAIL: "SAME_EMAIL",

  // Subscription
  NO_ACTIVE_SUBSCRIPTION: "NO_ACTIVE_SUBSCRIPTION",
  ALREADY_SUBSCRIBED: "ALREADY_SUBSCRIBED",
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  USE_DELETE_TO_DOWNGRADE: "USE_DELETE_TO_DOWNGRADE",
  TRIAL_NOT_APPLICABLE: "TRIAL_NOT_APPLICABLE",
  TRIAL_NOT_AVAILABLE: "TRIAL_NOT_AVAILABLE",
  TRIAL_ALREADY_USED: "TRIAL_ALREADY_USED",
  ALREADY_HAS_ACTIVE_SUBSCRIPTION: "ALREADY_HAS_ACTIVE_SUBSCRIPTION",
  MANUAL_BILLING_DISABLED: "MANUAL_BILLING_DISABLED",
  PLAN_ID_OR_CODE_REQUIRED: "PLAN_ID_OR_CODE_REQUIRED",
  PLAN_ID_AND_CODE_CONFLICT: "PLAN_ID_AND_CODE_CONFLICT",

  // Plan
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",

  // Promo / Coupon
  PROMO_NOT_FOUND: "PROMO_NOT_FOUND",
  PROMO_NOT_YET_VALID: "PROMO_NOT_YET_VALID",
  PROMO_EXPIRED: "PROMO_EXPIRED",
  PROMO_LIMIT_REACHED: "PROMO_LIMIT_REACHED",
  PROMO_ALREADY_REDEEMED: "PROMO_ALREADY_REDEEMED",
  COUPON_NOT_FOUND: "COUPON_NOT_FOUND",
  COUPON_NOT_ACTIVE_YET: "COUPON_NOT_ACTIVE_YET",
  COUPON_EXPIRED: "COUPON_EXPIRED",
  COUPON_LIMIT_REACHED: "COUPON_LIMIT_REACHED",
  COUPON_PER_USER_LIMIT_REACHED: "COUPON_PER_USER_LIMIT_REACHED",
  COUPON_ALREADY_REDEEMED: "COUPON_ALREADY_REDEEMED",
  COUPON_INVALID: "COUPON_INVALID",
  COUPON_NOT_ACTIVE: "COUPON_NOT_ACTIVE",
  COUPON_CANNOT_DELETE_REDEEMED: "COUPON_CANNOT_DELETE_REDEEMED",

  // Dictionary
  DICTIONARY_ENTRY_NOT_FOUND: "DICTIONARY_ENTRY_NOT_FOUND",
  FOLDER_NOT_FOUND: "FOLDER_NOT_FOUND",
  FOLDER_ALREADY_EXISTS: "FOLDER_ALREADY_EXISTS",
  VOCABULARY_LIMIT_REACHED: "VOCABULARY_LIMIT_REACHED",
  FOLDER_LIMIT_REACHED: "FOLDER_LIMIT_REACHED",
  FOLDERS_NOT_AVAILABLE: "FOLDERS_NOT_AVAILABLE",
  ENTRIES_NOT_BELONG_TO_USER: "ENTRIES_NOT_BELONG_TO_USER",
  FOLDERS_NOT_BELONG_TO_USER: "FOLDERS_NOT_BELONG_TO_USER",
  FOLDER_NOT_BELONG_TO_USER: "FOLDER_NOT_BELONG_TO_USER",
  WORD_OR_TOKEN_REQUIRED: "WORD_OR_TOKEN_REQUIRED",
  TRANSLATION_OR_TOKEN_REQUIRED: "TRANSLATION_OR_TOKEN_REQUIRED",
  TOKEN_MISSING_WORD_OR_TRANSLATION: "TOKEN_MISSING_WORD_OR_TRANSLATION",
  DUPLICATE_FOLDER_ORDER_IDS: "DUPLICATE_FOLDER_ORDER_IDS",
  FOLDER_ORDER_IDS_MISMATCH: "FOLDER_ORDER_IDS_MISMATCH",

  // AI Translation
  GEMINI_KEY_NOT_CONFIGURED: "GEMINI_KEY_NOT_CONFIGURED",
  GEMINI_PARSE_ERROR: "GEMINI_PARSE_ERROR",
  NOT_CHECHEN: "NOT_CHECHEN",
  LOCATION_NOT_SUPPORTED: "LOCATION_NOT_SUPPORTED",
  GEMINI_ERROR: "GEMINI_ERROR",
  DAILY_TRANSLATION_LIMIT_REACHED: "DAILY_TRANSLATION_LIMIT_REACHED",
  AI_CACHE_ENTRY_NOT_FOUND: "AI_CACHE_ENTRY_NOT_FOUND",
  ADMIN_GEMINI_KEY_NOT_CONFIGURED: "ADMIN_GEMINI_KEY_NOT_CONFIGURED",

  // Text / Reader
  TEXT_NOT_FOUND: "TEXT_NOT_FOUND",
  PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
  TEXT_PAGE_NOT_FOUND: "TEXT_PAGE_NOT_FOUND",
  TEXT_HAS_NO_PAGES: "TEXT_HAS_NO_PAGES",
  INVALID_PAGE_NUMBER: "INVALID_PAGE_NUMBER",
  ALREADY_REPORTED_TEXT: "ALREADY_REPORTED_TEXT",

  // Deck / Cards
  LEMMA_NOT_FOUND: "LEMMA_NOT_FOUND",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",

  // Feedback
  THREAD_NOT_FOUND: "THREAD_NOT_FOUND",
  REACTION_NOT_FOUND: "REACTION_NOT_FOUND",
  FEEDBACK_PROVIDE_LEMMA_OR_TEXT: "FEEDBACK_PROVIDE_LEMMA_OR_TEXT",

  // Highlight / Note
  HIGHLIGHT_NOT_FOUND: "HIGHLIGHT_NOT_FOUND",
  NOTE_NOT_FOUND: "NOTE_NOT_FOUND",

  // Phrasebook
  PHRASE_NOT_FOUND: "PHRASE_NOT_FOUND",
  PHRASE_PROGRESS_NOT_FOUND: "PHRASE_PROGRESS_NOT_FOUND",
  PHRASE_REVIEW_INVALID_QUALITY: "PHRASE_REVIEW_INVALID_QUALITY",

  // Token (word token)
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",

  // Suggestions
  SUGGESTION_NOT_FOUND: "SUGGESTION_NOT_FOUND",
  SUGGESTION_FIELD_NOT_EDITABLE: "SUGGESTION_FIELD_NOT_EDITABLE",
  SUGGESTION_PENDING_EXISTS: "SUGGESTION_PENDING_EXISTS",
  SUGGESTION_ALREADY_REVIEWED: "SUGGESTION_ALREADY_REVIEWED",
  SUGGESTION_INVALID_STATUS: "SUGGESTION_INVALID_STATUS",
  SUGGESTION_NO_TARGET: "SUGGESTION_NO_TARGET",
  SUGGESTION_INVALID_TYPE: "SUGGESTION_INVALID_TYPE",

  // Text submissions
  TEXT_SUBMISSION_NOT_FOUND: "TEXT_SUBMISSION_NOT_FOUND",
  TEXT_SUBMISSION_ALREADY_REVIEWED: "TEXT_SUBMISSION_ALREADY_REVIEWED",
  TEXT_SUBMISSION_SOURCE_REQUIRED: "TEXT_SUBMISSION_SOURCE_REQUIRED",
  TEXT_SUBMISSION_INVALID_STATUS: "TEXT_SUBMISSION_INVALID_STATUS",

  // Legal
  LEGAL_DOCUMENT_NOT_FOUND: "LEGAL_DOCUMENT_NOT_FOUND",
  LEGAL_DOCUMENT_ALREADY_EXISTS: "LEGAL_DOCUMENT_ALREADY_EXISTS",

  // Markup engine / Dictionary admin
  LEMMA_ALREADY_LINKED: "LEMMA_ALREADY_LINKED",
  SENSE_REQUIRED_FOR_EXAMPLE: "SENSE_REQUIRED_FOR_EXAMPLE",
  EMPTY_IMPORT_PAYLOAD: "EMPTY_IMPORT_PAYLOAD",
  CANNOT_DELETE_PRIMARY_HEADWORD: "CANNOT_DELETE_PRIMARY_HEADWORD",
  CANNOT_UNSET_PRIMARY_HEADWORD: "CANNOT_UNSET_PRIMARY_HEADWORD",
  SENSE_NOT_FOUND: "SENSE_NOT_FOUND",
  EXAMPLE_NOT_FOUND: "EXAMPLE_NOT_FOUND",
  HEADWORD_NOT_FOUND: "HEADWORD_NOT_FOUND",
  MORPH_FORM_NOT_FOUND: "MORPH_FORM_NOT_FOUND",

  // Admin: morphology
  LEMMA_ALREADY_EXISTS: "LEMMA_ALREADY_EXISTS",
  MORPH_FORM_ALREADY_EXISTS: "MORPH_FORM_ALREADY_EXISTS",
  MORPH_RULE_ALREADY_EXISTS: "MORPH_RULE_ALREADY_EXISTS",
  MORPH_RULE_NOT_FOUND: "MORPH_RULE_NOT_FOUND",
  FILE_REQUIRED: "FILE_REQUIRED",
  CSV_EMPTY: "CSV_EMPTY",

  // Admin: tags
  TAG_ALREADY_EXISTS: "TAG_ALREADY_EXISTS",
  TAG_NOT_FOUND: "TAG_NOT_FOUND",

  // Admin: text
  ONLY_COMPLETED_CAN_RESTORE: "ONLY_COMPLETED_CAN_RESTORE",
  VERSION_NOT_FOUND: "VERSION_NOT_FOUND",
  TEXT_PHRASE_ALREADY_EXISTS: "TEXT_PHRASE_ALREADY_EXISTS",
  TEXT_NOT_TOKENIZED: "TEXT_NOT_TOKENIZED",
  PHRASE_WORDS_NOT_FOUND: "PHRASE_WORDS_NOT_FOUND",
  OCCURRENCE_NOT_FOUND: "OCCURRENCE_NOT_FOUND",

  // Admin: billing
  LIFETIME_CANNOT_EXTEND: "LIFETIME_CANNOT_EXTEND",
  PAYMENT_FULLY_REFUNDED: "PAYMENT_FULLY_REFUNDED",
  PAYMENT_ALREADY_REFUNDED: "PAYMENT_ALREADY_REFUNDED",
  INVALID_REFUND_AMOUNT: "INVALID_REFUND_AMOUNT",
  PAYMENT_INVALID_REFUND_AMOUNT: "PAYMENT_INVALID_REFUND_AMOUNT",
  NO_RECIPIENT_EMAIL: "NO_RECIPIENT_EMAIL",
  PAYMENT_NO_RECIPIENT_EMAIL: "PAYMENT_NO_RECIPIENT_EMAIL",
  COUPON_PERCENT_TOO_HIGH: "COUPON_PERCENT_TOO_HIGH",
  COUPON_INVALID_AMOUNT: "COUPON_INVALID_AMOUNT",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PLAN_CANNOT_DELETE_HAS_SUBSCRIPTIONS: "PLAN_CANNOT_DELETE_HAS_SUBSCRIPTIONS",
  USER_ID_OR_EMAIL_REQUIRED: "USER_ID_OR_EMAIL_REQUIRED",

  // Admin: feature flags
  FEATURE_FLAG_ALREADY_EXISTS: "FEATURE_FLAG_ALREADY_EXISTS",
  FEATURE_FLAG_NOT_FOUND: "FEATURE_FLAG_NOT_FOUND",
  FEATURE_FLAG_OVERRIDE_NOT_FOUND: "FEATURE_FLAG_OVERRIDE_NOT_FOUND",
  INVALID_IS_ENABLED_FILTER: "INVALID_IS_ENABLED_FILTER",
  INVALID_FILTER_VALUE: "INVALID_FILTER_VALUE",

  // Admin: roles
  CANNOT_REVOKE_BASE_ROLE: "CANNOT_REVOKE_BASE_ROLE",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  ROLE_ASSIGNMENT_NOT_FOUND: "ROLE_ASSIGNMENT_NOT_FOUND",
  USER_ALREADY_HAS_ROLE: "USER_ALREADY_HAS_ROLE",
  USER_ROLE_ALREADY_ASSIGNED: "USER_ROLE_ALREADY_ASSIGNED",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_ALREADY_CANCELED: "SUBSCRIPTION_ALREADY_CANCELED",
  SUBSCRIPTION_CANNOT_EXTEND_LIFETIME: "SUBSCRIPTION_CANNOT_EXTEND_LIFETIME",

  // Admin: unknown words
  UNKNOWN_WORD_NOT_FOUND: "UNKNOWN_WORD_NOT_FOUND",

  // Admin: feedback
  CANNOT_TRANSFER_TO_SELF: "CANNOT_TRANSFER_TO_SELF",
  FEEDBACK_CANNOT_TRANSFER_TO_SELF: "FEEDBACK_CANNOT_TRANSFER_TO_SELF",
  ASSIGNEE_NOT_FOUND: "ASSIGNEE_NOT_FOUND",
  TARGET_ADMIN_NOT_FOUND: "TARGET_ADMIN_NOT_FOUND",

  // Admin: tokenization
  NO_CURRENT_TOKENIZATION: "NO_CURRENT_TOKENIZATION",
  TEXT_VOCABULARY_NOT_FOUND: "TEXT_VOCABULARY_NOT_FOUND",

  // Admin: phrasebook
  PHRASEBOOK_CATEGORY_NOT_FOUND: "PHRASEBOOK_CATEGORY_NOT_FOUND",
  PHRASEBOOK_PHRASE_NOT_FOUND: "PHRASEBOOK_PHRASE_NOT_FOUND",
  PHRASE_SUGGESTION_NOT_FOUND: "PHRASE_SUGGESTION_NOT_FOUND",

  // Admin: text (more specific aliases)
  TEXT_VERSION_NOT_FOUND: "TEXT_VERSION_NOT_FOUND",
  TEXT_VERSION_NOT_COMPLETED: "TEXT_VERSION_NOT_COMPLETED",
  PHRASE_OCCURRENCE_NOT_FOUND: "PHRASE_OCCURRENCE_NOT_FOUND",
  PHRASE_OCCURRENCE_ALREADY_EXISTS: "PHRASE_OCCURRENCE_ALREADY_EXISTS",

  // Admin: morphology (alias)
  MORPHOLOGY_RULE_NOT_FOUND: "MORPHOLOGY_RULE_NOT_FOUND",

  // Admin: system logs
  LOG_NOT_FOUND: "LOG_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
