import { PrismaPg } from "@prisma/adapter-pg";
import { Language, PrismaClient } from "@prisma/client";
import "dotenv/config";

const connectionString = process.env["DATABASE_URL"];
if (!connectionString) {
  throw new Error("DATABASE_URL environment variable is not set");
}
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

type PhraseInput = {
  original: string;
  translation: string;
  transliteration?: string;
  sortOrder: number;
};

type CategoryInput = {
  emoji: string;
  name: string;
  sortOrder: number;
  phrases: PhraseInput[];
};

export const seedPhrasebook = async () => {
  const allCategories: CategoryInput[] = [
    {
      emoji: "👋",
      name: "Приветствия и прощания",
      sortOrder: 0,
      phrases: [
        { original: "Марша вогІийла!", translation: "Здравствуй!", sortOrder: 0 },
        { original: "Марша догІийла!", translation: "Здравствуйте!", sortOrder: 1 },
        { original: "Марша Іойла!", translation: "Счастливо оставаться!", sortOrder: 2 },
        { original: "Марша гІойла!", translation: "Счастливо! (уходящему)", sortOrder: 3 },
        { original: "Ассалам Іалайкум!", translation: "Здравствуй! (к мужчинам)", sortOrder: 4 },
        { original: "Ва Іалайкум салам.", translation: "Здравствуйте! (ответ мужчин)", sortOrder: 5 },
        { original: "Іодика хуьлда хьан!", translation: "До свидания (ты)!", sortOrder: 6 },
        { original: "Іодика хуьлда шун!", translation: "До свидания (вы)!", sortOrder: 7 },
        { original: "Дукха вехийла!", translation: "Живи долго!", sortOrder: 8 },
      ],
    },
    {
      emoji: "🤝",
      name: "Знакомство и личная информация",
      sortOrder: 1,
      phrases: [
        { original: "Хьо мила ю (ву)?", translation: "Кто ты?", sortOrder: 0 },
        { original: "Со студент ю (ву).", translation: "Я студент(ка).", sortOrder: 1 },
        { original: "Хьан фамили муха ю?", translation: "Как ваша фамилия?", sortOrder: 2 },
        { original: "Сан фамили Вахаев ю.", translation: "Моя фамилия Вахаев.", sortOrder: 3 },
        { original: "Хьан цІе муха ю?", translation: "Как тебя зовут?", sortOrder: 4 },
        { original: "Сан цІе Султан ю.", translation: "Меня зовут Султан.", sortOrder: 5 },
        { original: "Хьан маса шо ду?", translation: "Сколько тебе лет?", sortOrder: 6 },
        { original: "Сан берхІитта шо ду.", translation: "Мне 18 лет.", sortOrder: 7 },
        { original: "Хьо мичара ву?", translation: "Ты откуда?", sortOrder: 8 },
        { original: "Со Гуьмсера ву.", translation: "Я из Гудермеса.", sortOrder: 9 },
        { original: "Хьан доттагІ мичара ву?", translation: "Откуда твой друг?", sortOrder: 10 },
        { original: "Сан доттагІ Шелара ву.", translation: "Мой друг из Шали.", sortOrder: 11 },
      ],
    },
    {
      emoji: "💊",
      name: "Самочувствие и здоровье",
      sortOrder: 2,
      phrases: [
        { original: "Муха Іаш ду шу?", translation: "Как поживаете вы?", sortOrder: 0 },
        { original: "Муха Іаш ву хьо?", translation: "Как поживаешь ты?", sortOrder: 1 },
        { original: "Муха Іаш ю иза?", translation: "Как поживает она?", sortOrder: 2 },
        { original: "Дика Іаш ву/ю иза.", translation: "Хорошо живёт он/она.", sortOrder: 3 },
        { original: "Могуш лелий?", translation: "Как здоровье?", sortOrder: 4 },
        { original: "И гуттара могуш ву.", translation: "Он всегда здоров.", sortOrder: 5 },
        { original: "И гуттара могуш хир ву.", translation: "Он всегда будет здоров.", sortOrder: 6 },
        { original: "Сан пІелг чІогІа лозу.", translation: "У меня очень болит палец.", sortOrder: 7 },
        { original: "Букъ лозу!", translation: "Спина болит!", sortOrder: 8 },
      ],
    },
    {
      emoji: "🏠",
      name: "Бытовые диалоги",
      sortOrder: 3,
      phrases: [
        { original: "ХІун оьшу хьуна?", translation: "Что вам нужно?", sortOrder: 0 },
        { original: "Цхьа ах кила налха ло суна.", translation: "Дайте полкило масла.", sortOrder: 1 },
        { original: "ХІинцца!", translation: "Сейчас!", sortOrder: 2 },
        { original: "Чувала мегара дуй?", translation: "Можно войти?", sortOrder: 3 },
        { original: "Чувала хьайна!", translation: "Входите!", sortOrder: 4 },
        { original: "Кху чохь вуй … Іаш?", translation: "Здесь живёт …?", sortOrder: 5 },
        { original: "Со ву иза-м. ЛадугІуш ву со!", translation: "Это я. Слушаю.", sortOrder: 6 },
        { original: "Хьан цІарах кехат деана.", translation: "На ваше имя пришло письмо.", sortOrder: 7 },
        { original: "Схьаэца хьайна!", translation: "Получите!", sortOrder: 8 },
        { original: "Баркалла!", translation: "Спасибо!", sortOrder: 9 },
        { original: "Дика ду!", translation: "Хорошо!", sortOrder: 10 },
        { original: "Со дІавогІу.", translation: "Я иду.", sortOrder: 11 },
        { original: "ЦІа волахьа!", translation: "Иди домой!", sortOrder: 12 },
        { original: "Схьаволахьа, хьайн куьйгаш дилий!", translation: "Иди сюда и помой руки!", sortOrder: 13 },
        { original: "ХІума юур яра вай.", translation: "Будем кушать.", sortOrder: 14 },
      ],
    },
    {
      emoji: "❓",
      name: "Вопросительные слова",
      sortOrder: 4,
      phrases: [
        { original: "Мича? Мичахьа?", translation: "Где? Куда?", sortOrder: 0 },
        { original: "Мичахьара?", translation: "Откуда?", sortOrder: 1 },
        { original: "Мила?", translation: "Кто?", sortOrder: 2 },
        { original: "ХІун?", translation: "Что?", sortOrder: 3 },
        { original: "Маца?", translation: "Когда?", sortOrder: 4 },
        { original: "Мел хан кхаччалц?", translation: "До какого времени?", sortOrder: 5 },
        { original: "Мича кхаччалц?", translation: "До какого места?", sortOrder: 6 },
        { original: "ХІунда?", translation: "Почему? Для чего?", sortOrder: 7 },
        { original: "Муха?", translation: "Как? Каким образом?", sortOrder: 8 },
        { original: "Муьлха?", translation: "Какой?", sortOrder: 9 },
        { original: "Стенан? Хьенан?", translation: "Чей? Чья?", sortOrder: 10 },
        { original: "Муьлханиг?", translation: "Который?", sortOrder: 11 },
        { original: "Маса?", translation: "Сколько?", sortOrder: 12 },
      ],
    },
    {
      emoji: "🕐",
      name: "Время и дата",
      sortOrder: 5,
      phrases: [
        { original: "МосалгІа сахьт ду?", translation: "Который час?", sortOrder: 0 },
        { original: "Мел хан яьлла вайна?", translation: "Который час? (другой вариант)", sortOrder: 1 },
        { original: "ШолгІачух ах даьлла.", translation: "Половина второго.", sortOrder: 2 },
        { original: "Тахана", translation: "Сегодня", sortOrder: 3 },
        { original: "Селхана", translation: "Вчера", sortOrder: 4 },
        { original: "Стомара", translation: "Позавчера", sortOrder: 5 },
        { original: "Кхана", translation: "Завтра", sortOrder: 6 },
        { original: "Лама", translation: "Послезавтра", sortOrder: 7 },
        { original: "Буса", translation: "Ночью", sortOrder: 8 },
        { original: "Сарахь", translation: "Вечером", sortOrder: 9 },
        { original: "Делкъера", translation: "С полудня", sortOrder: 10 },
        { original: "БІаьста", translation: "Весной", sortOrder: 11 },
        { original: "Аьхка", translation: "Летом", sortOrder: 12 },
        { original: "Гуьйре", translation: "Осенью", sortOrder: 13 },
      ],
    },
    {
      emoji: "🗺️",
      name: "Направление и место",
      sortOrder: 6,
      phrases: [
        { original: "СхьавогІу.", translation: "Идёт сюда.", sortOrder: 0 },
        { original: "ДІавоьду.", translation: "Идёт туда.", sortOrder: 1 },
        { original: "Со схьавеара.", translation: "Я приехал.", sortOrder: 2 },
        { original: "Цо дІавигира иза цига.", translation: "Он увёл его туда.", sortOrder: 3 },
        { original: "Цо схьавалийра иза кхуза.", translation: "Он привёл его сюда.", sortOrder: 4 },
        { original: "Кхуза", translation: "Сюда", sortOrder: 5 },
        { original: "Цига", translation: "Туда", sortOrder: 6 },
        { original: "Лакха", translation: "Вверх", sortOrder: 7 },
        { original: "Арахь", translation: "На улице, снаружи", sortOrder: 8 },
        { original: "Чохь", translation: "Внутри, дома", sortOrder: 9 },
        { original: "ТІе", translation: "На (поверхность)", sortOrder: 10 },
        { original: "КІел", translation: "Под", sortOrder: 11 },
        { original: "Хьалха", translation: "Впереди", sortOrder: 12 },
        { original: "ТІехьа", translation: "Позади", sortOrder: 13 },
      ],
    },
    {
      emoji: "💬",
      name: "Простые утверждения",
      sortOrder: 7,
      phrases: [
        { original: "Ваша хаза вехаш ву.", translation: "Брат хорошо живёт.", sortOrder: 0 },
        { original: "Йиша хаза ехаш ю.", translation: "Сестра хорошо живёт.", sortOrder: 1 },
        { original: "Цициг хаза ду.", translation: "Кошка красивая.", sortOrder: 2 },
        { original: "ЧІара мерза бу.", translation: "Рыба вкусная.", sortOrder: 3 },
        { original: "Майра кІант ву.", translation: "Храбрый парень.", sortOrder: 4 },
        { original: "Дика кІант ву цу юьртахь вехаш.", translation: "Хороший парень живёт в этом селе.", sortOrder: 5 },
        { original: "КІайн цІа ду юьртахь суна хаза хеташ.", translation: "Белый дом в селе мне нравится.", sortOrder: 6 },
        { original: "Тахана де дика ду.", translation: "Сегодня хорошая погода.", sortOrder: 7 },
        { original: "ГІуллакх муху ду?", translation: "Как дела?", sortOrder: 8 },
        { original: "И книга чІогІа хаза ю.", translation: "Эта книга очень интересна.", sortOrder: 9 },
      ],
    },
    {
      emoji: "🧳",
      name: "Принадлежность и отрицание",
      sortOrder: 8,
      phrases: [
        { original: "И тІоьрмиг хьенан бу?", translation: "Эта сумка чья?", sortOrder: 0 },
        { original: "Шун бу иза?", translation: "Ваша?", sortOrder: 1 },
        { original: "ХІан-хІа! И тІоьрмиг сан бац.", translation: "Нет, нет! Эта сумка не моя.", sortOrder: 2 },
        { original: "И тІоьрмиг Маликин бу.", translation: "Эта сумка Малики.", sortOrder: 3 },
        { original: "Иза цІахь вац.", translation: "Его нет дома.", sortOrder: 4 },
        { original: "Со ца кхетта.", translation: "Я не понял.", sortOrder: 5 },
        { original: "Хьо ца кхетта.", translation: "Ты не понял.", sortOrder: 6 },
        { original: "Иза ца кхетта.", translation: "Он не понял.", sortOrder: 7 },
        { original: "Тхо ца кхетта.", translation: "Мы не поняли.", sortOrder: 8 },
        { original: "Со ца кхета.", translation: "Я не понимаю.", sortOrder: 9 },
        { original: "Хьо ца кхета.", translation: "Ты не понимаешь.", sortOrder: 10 },
        { original: "Иза ца кхета.", translation: "Он не понимает.", sortOrder: 11 },
        { original: "Тхо ца кхета.", translation: "Мы не понимаем.", sortOrder: 12 },
        { original: "Уьш ца кхета.", translation: "Они не понимают.", sortOrder: 13 },
        { original: "ХІан-хІа!", translation: "Нет, нет!", sortOrder: 14 },
        { original: "Аса хІумма а алац.", translation: "Я ничего не скажу.", sortOrder: 15 },
        { original: "Цо хІумма а дац.", translation: "Он ничего не делает.", sortOrder: 16 },
        { original: "Аса книга ешац.", translation: "Я не читаю книгу.", sortOrder: 17 },
      ],
    },
    {
      emoji: "🗣️",
      name: "Вопросы с глаголами",
      sortOrder: 9,
      phrases: [
        { original: "Хьо базара воьдий?", translation: "Ты идёшь на базар?", sortOrder: 0 },
        { original: "Ахьа олий цуьнга?", translation: "Ты скажешь ему?", sortOrder: 1 },
        { original: "Книга йоьший ахьа?", translation: "Ты будешь читать книгу?", sortOrder: 2 },
        { original: "Яздо й ахь кехат?", translation: "Пишешь ли ты письмо?", sortOrder: 3 },
        { original: "Яздийр дуй ахь кехат?", translation: "Напишешь ли ты письмо?", sortOrder: 4 },
        { original: "Яздин ий ахь кехат?", translation: "Написал ли ты письмо?", sortOrder: 5 },
        { original: "Маца деана хьоьга кехат?", translation: "Когда ты получил письмо?", sortOrder: 6 },
        { original: "Мичахь садаьІна аша кху аьхка?", translation: "Где вы отдыхали этим летом?", sortOrder: 7 },
        { original: "Хьан аьлла иза шуьга?", translation: "Кто сказал вам это?", sortOrder: 8 },
        { original: "Сирникаш юй шуьгахь?", translation: "Спички есть у вас?", sortOrder: 9 },
      ],
    },
    {
      emoji: "🏃",
      name: "Глаголы движения",
      sortOrder: 10,
      phrases: [
        { original: "Со вогІу.", translation: "Я иду.", sortOrder: 0 },
        { original: "Хьо вогІу.", translation: "Ты идёшь.", sortOrder: 1 },
        { original: "И/иза вогІу.", translation: "Он/она идёт.", sortOrder: 2 },
        { original: "Тхо/вай догІуш ду.", translation: "Мы идём.", sortOrder: 3 },
        { original: "Шу догІуш ду.", translation: "Вы идёте.", sortOrder: 4 },
        { original: "Уьш/уьзаш богІуш бу.", translation: "Они идут.", sortOrder: 5 },
        { original: "Со соцу.", translation: "Я останавливаюсь.", sortOrder: 6 },
        { original: "Тхо соьцу.", translation: "Мы останавливаемся.", sortOrder: 7 },
        { original: "Со веха.", translation: "Я живу.", sortOrder: 8 },
        { original: "Тхо деха.", translation: "Мы живём.", sortOrder: 9 },
        { original: "Со воду.", translation: "Я бегу.", sortOrder: 10 },
        { original: "Тхо довду.", translation: "Мы бежим.", sortOrder: 11 },
        { original: "Аса туху.", translation: "Я бью.", sortOrder: 12 },
        { original: "Ахьа туху.", translation: "Ты бьёшь.", sortOrder: 13 },
        { original: "Цо туху.", translation: "Он бьёт.", sortOrder: 14 },
        { original: "Оха/вай туху.", translation: "Мы бьём.", sortOrder: 15 },
        { original: "Аша туху.", translation: "Вы бьёте.", sortOrder: 16 },
        { original: "Цара туху.", translation: "Они бьют.", sortOrder: 17 },
      ],
    },
    {
      emoji: "⏳",
      name: "Глагол «быть» и времена",
      sortOrder: 11,
      phrases: [
        { original: "Со вара.", translation: "Я был.", sortOrder: 0 },
        { original: "Хьо вара.", translation: "Ты был.", sortOrder: 1 },
        { original: "И/иза вара.", translation: "Он/она был(а).", sortOrder: 2 },
        { original: "Тхо дара.", translation: "Мы были.", sortOrder: 3 },
        { original: "Шу дара.", translation: "Вы были.", sortOrder: 4 },
        { original: "Уьш бара.", translation: "Они были.", sortOrder: 5 },
        { original: "Со хир ву.", translation: "Я буду.", sortOrder: 6 },
        { original: "Хьо хир ву.", translation: "Ты будешь.", sortOrder: 7 },
        { original: "И/иза хир ву.", translation: "Он/она будет.", sortOrder: 8 },
        { original: "Тхо хир ду.", translation: "Мы будем.", sortOrder: 9 },
        { original: "Шу хир ду.", translation: "Вы будете.", sortOrder: 10 },
        { original: "Уьш хир бу.", translation: "Они будут.", sortOrder: 11 },
        { original: "Аса оху.", translation: "Я пашу. (простое настоящее)", sortOrder: 12 },
        { original: "Со охуш ву.", translation: "Я пашущий есть. (составное настоящее)", sortOrder: 13 },
        { original: "Аса эхи.", translation: "Я только что вспахал. (недавнопрошедшее)", sortOrder: 14 },
        { original: "Аса эхира.", translation: "Я пропахал. (очевидно-прошедшее)", sortOrder: 15 },
        { original: "Аса аьхна.", translation: "Я пахал. (прошедшее совершенное)", sortOrder: 16 },
        { original: "Аса аьхнера.", translation: "Я давно вспахал. (давнопрошедшее)", sortOrder: 17 },
        { original: "Аса охура.", translation: "Я попахивал. (прошедшее многократное)", sortOrder: 18 },
        { original: "Аса охур.", translation: "Я вспашу. (будущее возможное)", sortOrder: 19 },
        { original: "Аса охур ду.", translation: "Я буду пахать. (будущее фактическое)", sortOrder: 20 },
        { original: "Аса латта охур ду.", translation: "Я буду пахать землю.", sortOrder: 21 },
        { original: "Аса книга йоьшур ю.", translation: "Я буду читать книгу.", sortOrder: 22 },
        { original: "Аса Іаж буур бу.", translation: "Я буду кушать яблоко.", sortOrder: 23 },
        { original: "Со вуьжур ву.", translation: "Я буду спать.", sortOrder: 24 },
        { original: "Тхо дуьйшур ду.", translation: "Мы будем спать.", sortOrder: 25 },
        { original: "Уьзаш буьйшур бу.", translation: "Они будут спать.", sortOrder: 26 },
      ],
    },
    {
      emoji: "🔄",
      name: "Виды и условные предложения",
      sortOrder: 12,
      phrases: [
        { original: "Аса кхуссу.", translation: "Я бросаю (однократно).", sortOrder: 0 },
        { original: "Аса кхуьссу.", translation: "Я бросаю много раз.", sortOrder: 1 },
        { original: "Со соцу.", translation: "Я останавливаюсь (однократно).", sortOrder: 2 },
        { original: "Со соьцу.", translation: "Я останавливаюсь много раз.", sortOrder: 3 },
        { original: "Аса лохку.", translation: "Я гоню (однократно).", sortOrder: 4 },
        { original: "Аса лоьхку.", translation: "Я гоню много раз.", sortOrder: 5 },
        { original: "Таса", translation: "Бросить (однократный вид)", sortOrder: 6 },
        { original: "Тийса", translation: "Бросать (многократный вид)", sortOrder: 7 },
        { original: "Мала", translation: "Выпить (однократный вид)", sortOrder: 8 },
        { original: "Мийла", translation: "Пить (многократный вид)", sortOrder: 9 },
        { original: "Хьовса", translation: "Смотреть (однократный вид)", sortOrder: 10 },
        { original: "Хьийса", translation: "Посматривать (многократный вид)", sortOrder: 11 },
        { original: "Лахка", translation: "Гнать (однократный вид)", sortOrder: 12 },
        { original: "Лехка", translation: "Подгонять (многократный вид)", sortOrder: 13 },
        { original: "Ахь бер лийчадахьара, цо наб дика йийр яра.", translation: "Если бы ты выкупал ребёнка, он хорошо спал бы.", sortOrder: 14 },
        { original: "Ахь асар дика динехьара, хьаьжкІаш дика хьекъар яра.", translation: "Если бы ты хорошо прополол, кукуруза уродилась бы хорошо.", sortOrder: 15 },
        { original: "Нагахь сарахь хьо со волчу вагІахь, вайшиъ театре гІур ву.", translation: "Если ты вечером ко мне придёшь, мы сходим в театр.", sortOrder: 16 },
        { original: "ХІинца мукъана лийчахьара хьо.", translation: "Выкупался бы ты хотя бы теперь.", sortOrder: 17 },
        { original: "Селхана лийчинехьара хьо.", translation: "Выкупался бы ты вчера.", sortOrder: 18 },
      ],
    },
    {
      emoji: "🔢",
      name: "Числительные",
      sortOrder: 13,
      phrases: [
        { original: "Цхьаъ", translation: "1", sortOrder: 0 },
        { original: "Шиъ", translation: "2", sortOrder: 1 },
        { original: "Кхоъ", translation: "3", sortOrder: 2 },
        { original: "Диъ", translation: "4", sortOrder: 3 },
        { original: "Пхиъ", translation: "5", sortOrder: 4 },
        { original: "Ялх", translation: "6", sortOrder: 5 },
        { original: "ВорхІ", translation: "7", sortOrder: 6 },
        { original: "БархІ", translation: "8", sortOrder: 7 },
        { original: "Исс", translation: "9", sortOrder: 8 },
        { original: "Итт", translation: "10", sortOrder: 9 },
        { original: "Цхьайтта", translation: "11", sortOrder: 10 },
        { original: "Шийтта", translation: "12", sortOrder: 11 },
        { original: "Кхойтта", translation: "13", sortOrder: 12 },
        { original: "Дейтта", translation: "14", sortOrder: 13 },
        { original: "Пхийтта", translation: "15", sortOrder: 14 },
        { original: "Ялхитта", translation: "16", sortOrder: 15 },
        { original: "ВуьрхІитта", translation: "17", sortOrder: 16 },
        { original: "БерхІитта", translation: "18", sortOrder: 17 },
        { original: "Ткъайоьсна", translation: "19", sortOrder: 18 },
        { original: "Ткъа", translation: "20", sortOrder: 19 },
        { original: "Ткъе цхьаъ", translation: "21", sortOrder: 20 },
        { original: "Ткъе шиъ", translation: "22", sortOrder: 21 },
        { original: "Ткъе итт", translation: "30", sortOrder: 22 },
        { original: "Шовзткъа", translation: "40", sortOrder: 23 },
        { original: "Шовзткъе итт", translation: "50", sortOrder: 24 },
        { original: "Кхузткъа", translation: "60", sortOrder: 25 },
        { original: "Дезткъе итт", translation: "90", sortOrder: 26 },
        { original: "БІе", translation: "100", sortOrder: 27 },
        { original: "Ши бІе", translation: "200", sortOrder: 28 },
        { original: "Кхо бІе", translation: "300", sortOrder: 29 },
        { original: "Эзар", translation: "1 000", sortOrder: 30 },
        { original: "Ши эзар", translation: "2 000", sortOrder: 31 },
        { original: "Миллион", translation: "1 000 000", sortOrder: 32 },
        { original: "ЦхьоалгІа", translation: "Первый (порядковое)", sortOrder: 33 },
        { original: "ШолгІа", translation: "Второй (порядковое)", sortOrder: 34 },
        { original: "КхоалгІа", translation: "Третий (порядковое)", sortOrder: 35 },
        { original: "ЦхьайтталгІа", translation: "Одиннадцатый (порядковое)", sortOrder: 36 },
        { original: "ШийтталгІа", translation: "Двенадцатый (порядковое)", sortOrder: 37 },
        { original: "КхойтталгІа", translation: "Тринадцатый (порядковое)", sortOrder: 38 },
        { original: "Цхьацца", translation: "По одному (разделительное)", sortOrder: 39 },
        { original: "Шишша", translation: "По два (разделительное)", sortOrder: 40 },
        { original: "Кхоккха", translation: "По три (разделительное)", sortOrder: 41 },
        { original: "Диъ-диъ", translation: "По четыре (разделительное)", sortOrder: 42 },
        { original: "Пхиппа", translation: "По пяти (разделительное)", sortOrder: 43 },
        { original: "Ший а", translation: "Двое (собирательное)", sortOrder: 44 },
        { original: "Кхоь а", translation: "Трое (собирательное)", sortOrder: 45 },
        { original: "Де а", translation: "Четверо (собирательное)", sortOrder: 46 },
        { original: "Пхе а", translation: "Пятеро (собирательное)", sortOrder: 47 },
        { original: "ВорхІе а", translation: "Семеро (собирательное)", sortOrder: 48 },
        { original: "БархІе а", translation: "Восьмеро (собирательное)", sortOrder: 49 },
        { original: "Иссе а", translation: "Девятеро (собирательное)", sortOrder: 50 },
        { original: "Итте а", translation: "Десятеро (собирательное)", sortOrder: 51 },
        { original: "Цкъа", translation: "Однажды (кратное)", sortOrder: 52 },
        { original: "Шозза", translation: "Дважды (кратное)", sortOrder: 53 },
        { original: "Кхузза", translation: "Трижды (кратное)", sortOrder: 54 },
        { original: "Доьазза", translation: "Четырежды (кратное)", sortOrder: 55 },
        { original: "Пхоьазза", translation: "Пятью (кратное)", sortOrder: 56 },
        { original: "Ах", translation: "Половина", sortOrder: 57 },
        { original: "ШолгІа дакъа", translation: "Вторая часть", sortOrder: 58 },
        { original: "КхоалгІа дакъа", translation: "Третья часть", sortOrder: 59 },
        { original: "ДоьалгІа дакъа", translation: "Четвёртая часть", sortOrder: 60 },
        { original: "ПхоьалгІа дакъа", translation: "Пятая часть", sortOrder: 61 },
        { original: "УьтталгІа дакъа", translation: "Десятая часть", sortOrder: 62 },
      ],
    },
    {
      emoji: "📊",
      name: "Вопросы о количестве",
      sortOrder: 14,
      phrases: [
        { original: "Маса книга ю?", translation: "Сколько книг?", sortOrder: 0 },
        { original: "Итт книга ю.", translation: "Десять книг.", sortOrder: 1 },
        { original: "Маса билет ду?", translation: "Сколько билетов?", sortOrder: 2 },
        { original: "Ши билет ду.", translation: "Два билета.", sortOrder: 3 },
        { original: "Мел хан яьлла?", translation: "Сколько времени прошло?", sortOrder: 4 },
        { original: "Итт сахьт даьлла.", translation: "Десять часов прошло.", sortOrder: 5 },
        { original: "Маса говр ю?", translation: "Сколько лошадей?", sortOrder: 6 },
        { original: "Кхо говр ю.", translation: "Три лошади.", sortOrder: 7 },
        { original: "Мел дара хьан ахча?", translation: "Сколько у тебя было денег?", sortOrder: 8 },
        { original: "Сан ши бІе туьма дара.", translation: "У меня было двести рублей.", sortOrder: 9 },
      ],
    },
    {
      emoji: "📏",
      name: "Единицы измерения и деньги",
      sortOrder: 15,
      phrases: [
        { original: "Метр", translation: "Метр", sortOrder: 0 },
        { original: "Кила", translation: "Килограмм", sortOrder: 1 },
        { original: "Километр", translation: "Километр", sortOrder: 2 },
        { original: "Чаккхарма", translation: "Верста", sortOrder: 3 },
        { original: "Сахьт", translation: "Час", sortOrder: 4 },
        { original: "Минот", translation: "Минута", sortOrder: 5 },
        { original: "Сом", translation: "Рубль", sortOrder: 6 },
        { original: "Кепек", translation: "Копейка", sortOrder: 7 },
        { original: "Туьма", translation: "Десять рублей", sortOrder: 8 },
        { original: "Эппаза", translation: "Двадцать копеек", sortOrder: 9 },
        { original: "Шай", translation: "Пять копеек", sortOrder: 10 },
        { original: "Мах", translation: "Цена, торговля", sortOrder: 11 },
        { original: "ГІуда", translation: "Штраф", sortOrder: 12 },
      ],
    },
    {
      emoji: "🧠",
      name: "Части тела",
      sortOrder: 16,
      phrases: [
        { original: "Kog", translation: "Нога", sortOrder: 0 },
        { original: "БІаьрг", translation: "Глаз", sortOrder: 1 },
        { original: "Церг", translation: "Зуб", sortOrder: 2 },
        { original: "Мара", translation: "Нос", sortOrder: 3 },
        { original: "Куьг", translation: "Рука", sortOrder: 4 },
        { original: "ПІелг", translation: "Палец", sortOrder: 5 },
        { original: "Букъ", translation: "Спина", sortOrder: 6 },
      ],
    },
    {
      emoji: "📅",
      name: "Существительные: время",
      sortOrder: 17,
      phrases: [
        { original: "Де", translation: "День", sortOrder: 0 },
        { original: "Шо", translation: "Год", sortOrder: 1 },
        { original: "Бутт", translation: "Месяц", sortOrder: 2 },
        { original: "КІира", translation: "Неделя", sortOrder: 3 },
        { original: "Сахьт", translation: "Час", sortOrder: 4 },
        { original: "Минот", translation: "Минута", sortOrder: 5 },
        { original: "Суьйре", translation: "Вечер", sortOrder: 6 },
        { original: "Буьйса", translation: "Ночь", sortOrder: 7 },
        { original: "Гуьйре", translation: "Осень", sortOrder: 8 },
      ],
    },
    {
      emoji: "🌿",
      name: "Существительные: природа",
      sortOrder: 18,
      phrases: [
        { original: "Латта", translation: "Земля", sortOrder: 0 },
        { original: "Хи", translation: "Вода", sortOrder: 1 },
        { original: "Малх", translation: "Солнце", sortOrder: 2 },
        { original: "ДогІа", translation: "Дождь", sortOrder: 3 },
        { original: "Стиг", translation: "Небо", sortOrder: 4 },
        { original: "Лам", translation: "Гора", sortOrder: 5 },
        { original: "Аре", translation: "Поле, степь", sortOrder: 6 },
        { original: "Некъ", translation: "Дорога", sortOrder: 7 },
        { original: "ХІорд", translation: "Море", sortOrder: 8 },
        { original: "Шело", translation: "Мороз", sortOrder: 9 },
      ],
    },
    {
      emoji: "🏡",
      name: "Существительные: дом и быт",
      sortOrder: 19,
      phrases: [
        { original: "ЦІа", translation: "Дом", sortOrder: 0 },
        { original: "Чоь", translation: "Внутренность, комната", sortOrder: 1 },
        { original: "Тхов", translation: "Крыша", sortOrder: 2 },
        { original: "Кор", translation: "Окно", sortOrder: 3 },
        { original: "Пеша", translation: "Печь", sortOrder: 4 },
        { original: "Стол", translation: "Стол", sortOrder: 5 },
        { original: "ГІант", translation: "Стул", sortOrder: 6 },
        { original: "ЦІенкъа", translation: "Пол", sortOrder: 7 },
        { original: "Дитт", translation: "Дерево", sortOrder: 8 },
        { original: "Керт", translation: "Забор, двор", sortOrder: 9 },
        { original: "ТІоьрмиг", translation: "Сумка", sortOrder: 10 },
        { original: "Кехат", translation: "Письмо, бумага", sortOrder: 11 },
        { original: "Книга", translation: "Книга", sortOrder: 12 },
        { original: "Билет", translation: "Билет", sortOrder: 13 },
      ],
    },
    {
      emoji: "➡️",
      name: "Послелоги",
      sortOrder: 20,
      phrases: [
        { original: "Чу", translation: "В, внутрь", sortOrder: 0 },
        { original: "Ара", translation: "Вне, наружу", sortOrder: 1 },
        { original: "ТІе", translation: "На", sortOrder: 2 },
        { original: "КІел", translation: "Под", sortOrder: 3 },
        { original: "Хьалха", translation: "Впереди", sortOrder: 4 },
        { original: "ТІехьа", translation: "Позади", sortOrder: 5 },
        { original: "ТІаьхьа", translation: "После", sortOrder: 6 },
        { original: "Герга", translation: "Вблизи", sortOrder: 7 },
        { original: "Гена", translation: "Далеко", sortOrder: 8 },
        { original: "Гергга", translation: "Вплотную", sortOrder: 9 },
        { original: "Генна", translation: "Подальше", sortOrder: 10 },
        { original: "Хьалхха", translation: "В самый перед", sortOrder: 11 },
        { original: "ТІехула", translation: "Через (поверх)", sortOrder: 12 },
        { original: "Чухула", translation: "Через (сквозь)", sortOrder: 13 },
        { original: "КІелхула", translation: "Из-под", sortOrder: 14 },
      ],
    },
    {
      emoji: "📝",
      name: "Наречия",
      sortOrder: 21,
      phrases: [
        { original: "Дика", translation: "Хорошо (образа действия)", sortOrder: 0 },
        { original: "Хаза", translation: "Красиво (образа действия)", sortOrder: 1 },
        { original: "Чехка", translation: "Быстро (образа действия)", sortOrder: 2 },
        { original: "Сиха", translation: "Скоро, быстро (образа действия)", sortOrder: 3 },
        { original: "Меллаша", translation: "Тихо (образа действия)", sortOrder: 4 },
        { original: "Шалха", translation: "Вдвойне (образа действия)", sortOrder: 5 },
        { original: "ЧІогІа", translation: "Очень, сильно (степени)", sortOrder: 6 },
        { original: "Вуно", translation: "Очень (степени)", sortOrder: 7 },
        { original: "Іаламат", translation: "Очень (степени)", sortOrder: 8 },
        { original: "Инзаре", translation: "Очень (степени)", sortOrder: 9 },
        { original: "ЖимI-жимма", translation: "Понемногу (степени)", sortOrder: 10 },
        { original: "Гуттар", translation: "Всегда (времени)", sortOrder: 11 },
        { original: "ХІинцца", translation: "Сейчас (времени)", sortOrder: 12 },
        { original: "Тахана", translation: "Сегодня (времени)", sortOrder: 13 },
        { original: "Селхана", translation: "Вчера (времени)", sortOrder: 14 },
        { original: "Кхана", translation: "Завтра (времени)", sortOrder: 15 },
        { original: "Стомара", translation: "Позавчера (времени)", sortOrder: 16 },
        { original: "Лама", translation: "Послезавтра (времени)", sortOrder: 17 },
        { original: "Кхуза", translation: "Сюда (места)", sortOrder: 18 },
        { original: "Цига", translation: "Туда (места)", sortOrder: 19 },
        { original: "Лакха", translation: "Вверх (места)", sortOrder: 20 },
        { original: "Арахь", translation: "Снаружи (места)", sortOrder: 21 },
        { original: "Чохь", translation: "Внутри (места)", sortOrder: 22 },
        { original: "Цундела", translation: "Поэтому (причины)", sortOrder: 23 },
        { original: "Сонталла", translation: "Сдуру (причины)", sortOrder: 24 },
      ],
    },
    {
      emoji: "😮",
      name: "Междометия",
      sortOrder: 22,
      phrases: [
        { original: "ЭхІ!", translation: "Эх! Ой! (удивление, восторг, досада)", sortOrder: 0 },
        { original: "Ватта!", translation: "Ой! (удивление — только женщины)", sortOrder: 1 },
        { original: "ОххІай!", translation: "Ох! (усталость, боль, скорбь)", sortOrder: 2 },
        { original: "Вadaday!", translation: "Ужас! (только женщины)", sortOrder: 3 },
        { original: "ХІай-хІай!", translation: "Ага! (ироническое злорадство)", sortOrder: 4 },
        { original: "ХІа", translation: "— (испуг)", sortOrder: 5 },
      ],
    },
    {
      emoji: "🔤",
      name: "Словообразование",
      sortOrder: 23,
      phrases: [
        { original: "ДогцІена", translation: "Чистосердечный (Дог=сердце + цІена=чистый)", sortOrder: 0 },
        { original: "ДогІаьржа", translation: "Зловредный (Дог + Іаьржа=чёрный)", sortOrder: 1 },
        { original: "Догмайра", translation: "Храбрый (Дог + майра=храбрый)", sortOrder: 2 },
        { original: "СапаргІат", translation: "Спокойный (Са=душа + паргІат=свободный)", sortOrder: 3 },
      ],
    },
    {
      emoji: "📖",
      name: "Пословицы и поговорки",
      sortOrder: 24,
      phrases: [
        { original: "Тхуна тІом ца беза, тхуна машар беза.", translation: "Мы не хотим войны, мы хотим мира.", sortOrder: 0 },
        { original: "Дика кІант — кема, вон кІант — гема.", translation: "Хороший сын — корабль, плохой сын — путы.", sortOrder: 1 },
        { original: "Дика сте — моз, вон сте — борз.", translation: "Хорошая жена — мёд, плохая жена — волчица.", sortOrder: 2 },
        { original: "ТІамо стаг вина вац, тІамо стаг вийна.", translation: "Война человека не родила, война убила.", sortOrder: 3 },
        { original: "Сих ма ло, виц ма ло.", translation: "Не спеши и не забывайся.", sortOrder: 4 },
        { original: "Палс маббу хеца ког.", translation: "По паласу и ноги протягивай.", sortOrder: 5 },
        { original: "Чорпано вагийнчо хина хІуп баьхна.", translation: "Обжёгшись на супе, дует на воду.", sortOrder: 6 },
        { original: "Іаж Іожана гена ца бужу.", translation: "Яблоко от яблони недалеко падает.", sortOrder: 7 },
        { original: "Іиллинчу барзал лелла цхьогал тоьлла.", translation: "Бегающая лисица лучше лежащего волка.", sortOrder: 8 },
        { original: "Собар толаман меттамотт бу.", translation: "Выдержка — лежбище победы.", sortOrder: 9 },
        { original: "Гинарг хезначул чІогІа ду.", translation: "Увиденное лучше слышанного.", sortOrder: 10 },
        { original: "Дукха лер дети делахь а, цалер а ду деши-м.", translation: "Если говорливость — серебро, то молчание — золото.", sortOrder: 11 },
        { original: "Стаг вовза лаахь, цуьнан уьйрашка хьажа.", translation: "Хочешь узнать человека — посмотри, с кем он водится.", sortOrder: 12 },
        { original: "Дукха диъча, моз а хета къаьхьа.", translation: "И мёд горчит, когда его много съешь.", sortOrder: 13 },
        { original: "Нанас бер дилхича дакхадо.", translation: "Мать кормит дитя, когда оно заплачет.", sortOrder: 14 },
        { original: "Церг йоцуш борз ца хуьлу.", translation: "Волк не бывает без зубов.", sortOrder: 15 },
        { original: "Бартболчу цицигаша бартбоцу берзалой эшийна.", translation: "Дружные кошки победили недружных волков.", sortOrder: 16 },
        { original: "Бартбоцчу доьзалехь беркат хир дац.", translation: "В недружной семье добра не будет.", sortOrder: 17 },
        { original: "Ваша ваша вац, и хьан доттагІ вацахь.", translation: "Брат — не брат, если он тебе не друг.", sortOrder: 18 },
        { original: "ДоттагІ шираниг тоьлу, керт керланиг тоьлу.", translation: "Друг лучше старый, а забор новый.", sortOrder: 19 },
        { original: "Хазачу дашо Іуьргара лаьхьа баьккхина.", translation: "Красивое слово из норы змею вытащило.", sortOrder: 20 },
        { original: "Дохнаца хьекъал эцалур дац.", translation: "Богатством ума не купишь.", sortOrder: 21 },
        { original: "Юург — дегІан кхача, наб — син кхача.", translation: "Еда — пища тела, сон — пища души.", sortOrder: 22 },
        { original: "ЦІей, хий цхьаьна тарлац.", translation: "Огонь и вода не уживаются.", sortOrder: 23 },
        { original: "Хиэ хьер хьийзайо.", translation: "Вода мельницу крутит.", sortOrder: 24 },
        { original: "Нехан говро ирхе дика йоккху.", translation: "Чужая лошадь подъём хорошо берёт.", sortOrder: 25 },
        { original: "Маха леллачухула тай а лела.", translation: "Куда игла, туда и нить.", sortOrder: 26 },
        { original: "Газа иккхинчухула буьхьиг а иккхина.", translation: "Куда коза, туда и козлёнок.", sortOrder: 27 },
        { original: "Шозза аьлларг хьерахь а хезна.", translation: "Дважды сказанное и на мельнице услышали.", sortOrder: 28 },
        { original: "Іиллинчу тІулга кІел хи ца кхаьчна.", translation: "Под лежащий камень вода не течёт.", sortOrder: 29 },
        { original: "Ла мел дийгІи, татанаш сов хеза.", translation: "Чем больше слушаешь, тем больше шума слышно.", sortOrder: 30 },
        { original: "Бакъдерг бен цІена хилац.", translation: "Только правда чиста.", sortOrder: 31 },
        { original: "Охуш аьлларг оруш карийна.", translation: "Сказанное при пахоте нашлось при молотьбе.", sortOrder: 32 },
        { original: "Сту белча — жижиг, ворда йоьхча — дечиг.", translation: "Бык подох — мясо, арба сломалась — дрова.", sortOrder: 33 },
        { original: "Чохь диснарг — деши, арадаьлларг — дети.", translation: "Что осталось — золото, что ушло — серебро.", sortOrder: 34 },
      ],
    },
  ];

  let categoryCount = 0;
  let phraseCount = 0;

  for (const cat of allCategories) {
    const created = await prisma.phrasebookCategory.create({
      data: {
        emoji: cat.emoji,
        name: cat.name,
        sortOrder: cat.sortOrder,
      },
    });
    categoryCount++;

    for (const p of cat.phrases) {
      await prisma.phrasebookPhrase.create({
        data: {
          categoryId: created.id,
          original: p.original,
          transliteration: p.transliteration ?? "",
          translation: p.translation,
          lang: Language.CHE,
          sortOrder: p.sortOrder,
        },
      });
      phraseCount++;
    }
  }

  console.log(
    `✅  Phrasebook seed: создано категорий — ${categoryCount}, фраз — ${phraseCount}`,
  );
};
