// Bigrams must come before single chars — matched longest-first
export const CYRILLIC_TO_LATIN_BIGRAMS: [string, string][] = [
  ['гӀ', 'ġ'],
  ['хь', 'ẋ'],
  ['хӀ', 'h'],
  ['цӀ', 'ċ'],
  ['чӀ', 'ç̇'],
  ['кх', 'q'],
  ['къ', 'q̇'],
  ['кӀ', 'kh'],
  ['пӀ', 'ph'],
  ['тӀ', 'th'],
  ['аь', 'ä'],
  ['оь', 'ö'],
  ['уь', 'ü'],
  ['юь', 'yü'],
  ['яь', 'yä'],
];

export const CYRILLIC_TO_LATIN_SINGLE: [string, string][] = [
  ['а', 'a'],
  ['б', 'b'],
  ['в', 'v'],
  ['г', 'g'],
  ['д', 'd'],
  // е handled separately: word-start → 'ye', medial → 'e'
  ['ж', 'ƶ'],
  ['з', 'z'],
  ['и', 'i'],
  ['й', 'y'],
  ['к', 'k'],
  ['л', 'l'],
  ['м', 'm'],
  // н handled separately: nazalized → 'ŋ', else → 'n'
  ['о', 'o'],
  ['п', 'p'],
  ['р', 'r'],
  ['с', 's'],
  ['т', 't'],
  ['у', 'u'],
  ['ф', 'f'],
  ['х', 'x'],
  ['ц', 'c'],
  ['ч', 'ç'],
  ['ш', 'ş'],
  ['щ', 'şç'],
  ['ъ', 'ə'],
  ['ы', 'i'],
  ['э', 'e'],
  ['ю', 'yu'],
  ['я', 'ya'],
  ['ё', 'yo'],
  ['Ӏ', 'j'],
  ['е', 'e'], // fallback; word-start handled in service
];
